apiVersion: v1
kind: Pod
metadata:
  name: low-pi6
  labels:
    k8s-app: low
    preemptible_job: "true"
spec:
  containers:
    - image: ccr.ccs.tencentyun.com/tkeimages/stress-ng:v0.12.09
      command:
        - stress-ng
        - --vm-hang
        - "3600"
        - --vm
        - "2"
        - --vm-bytes
        - "2G"
      name: stress
      volumeMounts:
        - mountPath: /data
          name: data
  volumes:
    - hostPath:
        path: /data/dd
        type: DirectoryOrCreate
      name: data
---
apiVersion: v1
kind: Pod
metadata:
  name: low-pi2
  labels:
    k8s-app: low
    preemptible_job: "true"
spec:
  containers:
    - image: ccr.ccs.tencentyun.com/tkeimages/stress-ng:v0.12.09
      command:
        - stress-ng
        - --vm-hang
        - "3600"
        - --vm
        - "2"
        - --vm-bytes
        - "3.5G"
      name: stress
      volumeMounts:
        - mountPath: /data
          name: data
  volumes:
    - hostPath:
        path: /data/dd
        type: DirectoryOrCreate
      name: data

