apiVersion: ensurance.crane.io/v1alpha1
kind: NodeQOS
metadata:
  name: eviction-on-high-cpu-usage-percent
spec:
  nodeQualityProbe:
    nodeLocalGet:
      localCacheTTLSeconds: 60
    timeoutSeconds: 10
  rules:
    - actionName: eviction
      avoidanceThreshold: 2
      metricRule:
        name: memory_total_usage
        value: 5000000000
      name: cpu-usage-percent
      restoreThreshold: 2
      strategy: None