apiVersion: analysis.crane.io/v1alpha1
kind: ConfigSet
configs:
  - targets: []
    properties:
      resource.cpu-request-percentile: "0.98"
      replicas.workload-min-replicas: "3"
      replicas.pod-min-ready-seconds: "30"
      replicas.pod-available-ratio: "0.5"
      replicas.default-min-replicas: "3"
      replicas.max-replicas-factor: "3"
      replicas.min-cpu-usage-threshold: "1"
      replicas.fluctuation-threshold: "1.5"
      replicas.min-cpu-target-utilization: "30"
      replicas.max-cpu-target-utilization: "75"
      replicas.cpu-target-utilization: "50"
      replicas.cpu-percentile: "95"
      replicas.reference-hpa: "true"